empleado/applications/departamento/urls.py
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'listar-todo-departamento', 
        views.DepartamentoListView.as_view(),
        name = 'departamento'
    ),
]

empleado/applications/empleados/urls.py
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name = 'inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListaAllEmpleados.as_view(),
        name = 'empleados_all'
    ),
    path(
        'listar-by-area/<shortname>/', 
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_detail'),
    path('buscar-empleado/', views.ListEmpleadosByWork.as_view()),
    path('lista-habilidaes-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name = 'empleados_detalle'
    ),
    path('add-empleado/', views.EmpleadoCreateView.as_view()),
]

empleado/applications/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.IndexView.as_view()),
    path('lista/', views.PruebaListView.as_view()),
    path('lista-prueba/', views.ModeloPruebaListView.as_view()),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
]

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la Empresa'
        ordering = ['name']
        unique_together = ('name', 'short_name')
    
    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name

empleado/applications/empleados/models.py
from django.db import models
from applications.departamento.models import Departamento


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades del Empleado'

    def __str__(self):
        return str(self.id)+ ' - '+ self.habilidad

# Create your models here.
class Empleado(models.Model):
    """ Datos empleado """

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('apellidos', max_length=50)
    job = models.CharField('trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = models.TextField()

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ['first_name']

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name
    

empleado/applications/home/models.py
from django.db import models

# Create your models here.
class Prueba(models.Model):
    titulo = models.CharField(max_length=50)
    subtitulo = models.CharField(max_length=50)

empleado/applications/departamento/views.py
from django.shortcuts import render

from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import  (
    ListView, 
    DetailView,
    CreateView,
    TemplateView
)

from .models import Departamento
# Create your views here.


class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'

empleado/applications/empleados/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import  (
    ListView, 
    DetailView,
    CreateView,
    TemplateView
)

from .models import Empleado
# Create your views here.


class InicioView(TemplateView):
    template_name = "inicio.html"




class ListaAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 3
    ordering = 'id'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name__icontains = palabra_clave
        )
        return lista


class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'id'
    context_object_name = 'empleados'
    model = Empleado


class ListByAreaEmpleado(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        # se recibe variable de la url
        area = self.kwargs['shortname'] 
        lista = Empleado.objects.filter(
            departamento__short_name = area
        )
        return lista

class ListEmpleadosByWork(ListView):
    """ Lista a través de empleados """
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('******************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        print('lista resultado: ', lista)
        return lista

class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=1)
        print(empleado.habilidades.all())
        return empleado.habilidades.all()
    

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"


class EmpleadoCreateView(CreateView):
    template_name = 'persona/add.html'
    model = Empleado
    fields = ('__all__')
    success_url = '.'

empleado/applications/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from .models import Prueba
# Create your views here.
class IndexView(TemplateView):
    template_name = 'home/home.html'

class PruebaListView(ListView):
    template_name = 'home/lista.html'
    queryset = ['A', 'B', 'C']
    context_object_name = 'lista_prueba'

class ModeloPruebaListView(ListView):
    model = Prueba
    template_name = "home/pruebas.html"
    context_object_name = 'lista_prueba_db'

empleado/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>
    {% block content %} {% endblock content %}

    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
        $(document).foundation();
    </script>
</body>
</html>

empleado/templates/departamento/lista.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Página de Inicio {% endblock title %}

{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Departamentos</h1>
        <table>
            <tbody>
                {% for departamentos in departamentos %}
                <tr>
                    <td>{{departamentos.name}}</td>
                    <td>{{departamentos.short_name}}</td>
                    <td></td>
                    <td>
                        <div class="button-group">
                            <a class="button warning" href="{% url 'persona_app:empleados_area' departamentos.short_name %}">Ver Empleados</a>
                            <!-- <a class="button danger">Eliminar</a> -->
                        </div>
                    </td>   
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

empleado/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Mi primera Página</h1>
    <p>Este es un ejemplo de primera pagina desde la pagina template</p>
</body>
</html>

empleado/templates/home/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Listas desde template</h1>
    {{ lista_prueba }}
</body>
</html>

empleado/templates/home/pruebas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lista desde una BD</h1>
    {{ lista_prueba_db }}

    <ul>
        
        {% for prueba in lista_prueba_db %}
            <li>{{ prueba.titulo }}</li>
        {% endfor %}
            
    </ul>
</body>
</html>

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li ><a href="{% url 'persona_app:inicio' %}">Empleados</a></li>
        <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:departamento' %}">Departamento</a></li>
        <li><a href="#">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><button type="button" class="button">Registrar Nuevo</button></li>
      </ul>
    </div>
  </div>

empleado/templates/inicio.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Página de Inicio {% endblock title %}

{% block content %} 

    {% include 'includes/header.html' %}
    <!-- inicio de portada -->
    <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
        <div class="orbit-wrapper">
            <div class="orbit-controls">
                <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
                <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
            </div>
            <ul class="orbit-container">
                <li class="is-active orbit-slide">
                    <figure class="orbit-figure">
                        <img class="orbit-image" src="{% static 'img/1.jpg' %}" alt="Space">
                        <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
                    </figure>
                </li>
                <li class="orbit-slide">
                    <figure class="orbit-figure">
                        <img class="orbit-image" src="{% static 'img/2.jpg' %}" alt="Space">
                        <figcaption class="orbit-caption">Lets Rocket!</figcaption>
                    </figure>
                </li>
                <li class="orbit-slide">
                    <figure class="orbit-figure">
                        <img class="orbit-image" src="{% static 'img/3.jpg' %}" alt="Space">
                        <figcaption class="orbit-caption">Encapsulating</figcaption>
                    </figure>
                </li>
            </ul>
        </div>
        <nav class="orbit-bullets">
            <button class="is-active" data-slide="0">
                <span class="show-for-sr">First slide details.</span>
                <span class="show-for-sr" data-slide-active-label>Current Slide</span>
            </button>
            <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
            <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
            <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
        </nav>
    </div>
    <!-- FIN inicio de portada -->

    <!-- Bloque Bienvenida -->
    <div class="grid-x align-center">
        <h1 class="cell large-8" style="font-size: 20px; text-align: center;">BIENVENIDO AL SISTEMA DE REGISTROS DE EMPLEADOS</h1>
        <div class="cell large-7">
            <div class="callout success">
                <h5>This is a callout.</h5>
                <p>It has an easy to override visual style, and is appropriately subdued.</p>
                <a href="#">It's dangerous to go alone, take this.</a>
            </div>
        </div>
    </div>
    <!-- FIN Bloque Bienvenida -->
{% endblock content %}

empleado/templates/persona/add.html
<h1>Formulario </h1>

<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">AGREGAR</button>
</form>

empleado/templates/persona/by_kword.html
<h1>Buscar persona por palabra caja de texto</h1>
<form action="" method="get">{% csrf_token %}
    <input type="text" name="kword" id="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>

<ul>
    {% for e in empleados %}
    <li>{{ e }}</li>
    {% endfor %}
</ul>

empleado/templates/persona/detail_empleado.html
<h1>Detalle de un empleado {{ titulo}}</h1>
{{ empleado }}

<h3>Todos los empleados</h3>
{{ empleado.first_name }}
{{ empleado.last_name }}
{{ empleado.job }}
{{ empleado.departamento }}
{{ empleado.avatar }}
{{ empleado.hoja_vida }

empleado/templates/persona/habilidades.html
<h1>HAbilidades Empleado</h1>
<ul>
    {% for h in habilidades %}
    <li>{{ h }}</li>
    {% endfor %}
</ul>

empleado/templates/persona/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Página de Inicio {% endblock title %}

{% block content %} 

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h3>Lista empleados</h3>
            </div>
            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
                </div>
                <div class="cell large-2">
                    <button class="submit success button">Guardar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="10">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td>
                                <div class="button-group">
                                    <a class="button warning" href="{% url 'persona_app:empleados_detalle' e.id %}">Ver</a>
                                    <a class="button danger">Eliminar</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous ">
                            <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        
                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endif %}
                        
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
    
    
{% endblock content %}

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Página de Inicio {% endblock title %}
{% block content %} 
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Empleados por area</h1>
        <table>
            <thead>
                <tr>
                    <th width="10">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCIÓN</th>
                </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td>
                        <div class="button-group">
                            <a class="button warning" href="{% url 'persona_app:empleados_detalle' e.id %}">Ver</a>
                            <a class="button danger">Eliminar</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

empleado/templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Página de Inicio {% endblock title %}

{% block content %} 

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h3>Lista empleados</h3>
            </div>
            
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="10">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td>
                                <div class="button-group">
                                    <a class="button success" href="{% url 'persona_app:empleados_detalle' e.id %}">Ver</a>
                                    <a class="button alert">Eliminar</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous ">
                            <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        
                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endif %}
                        
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
    
    
{% endblock content %}